[package]
name = "thats_a_wrap"
version = "0.1.0"
authors = ["Alex King <alex.king@and.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
